# fly.toml app configuration file generated for nostale-raid-helper-bot on 2023-05-19T20:46:42+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nostale-raid-helper-bot"
primary_region = "cdg"
